### ISSUE TITLE
Crash app when I launch it

### ISSUE THREAD

**Issue by NooAn** [InflationX/ViewPump#18]
07-19 11:35:53.054 2610-2610/ connect.android.mobile E/dalvikvm: Could not find class 'io.github.inflationx.viewpump.FallbackViewCreationInterceptor', referenced from method io.github.inflationx.viewpump.ViewPump.<init>
07-19 11:35:53.054 2610-2610/ connect.android.mobile E/dalvikvm: Could not find class 'io.github.inflationx.viewpump.InterceptorChain', referenced from method io.github.inflationx.viewpump.ViewPump.inflate
07-19 11:35:53.074 2610-2626/ connect.android.mobile E/dalvikvm: Could not find class 'android.app.job.JobScheduler', referenced from method com.google.android.gms.internal.iu.z
07-19 11:35:53.084 2610-2626/ connect.android.mobile E/dalvikvm: Could not find class 'android.app.job.JobScheduler', referenced from method com.google.android.gms.internal.iu.a
07-19 11:35:53.084 2610-2610/ connect.android.mobile E/AndroidRuntime: FATAL EXCEPTION: main
Process:  connect.android.mobile, PID: 2610
java.lang.NoClassDefFoundError: io.github.inflationx.viewpump.FallbackViewCreationInterceptor
at io.github.inflationx.viewpump.ViewPump.<init>(SourceFile:29)
at io.github.inflationx.viewpump.ViewPump.<init>(SourceFile:10)
at io.github.inflationx.viewpump.ViewPump$Builder.build(SourceFile:143)
at  connect.android.Application.onCreate(SourceFile:69)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4344)
at android.app.ActivityThread.access$1500(ActivityThread.java:135)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5017)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
at dalvik.system.NativeStart.main(Native Method)

This crash was found out in android 4.4 emulator. But not for each device. What is the reason?

**Comment by jbarr21** [comment]
Wasn't able to repro this on Android 4.4 emulator, but maybe a proguard or primary dex pattern issue
