### ISSUE TITLE
NonSdkApiUsedViolation for LayoutInflater.mConstructorArgs

### ISSUE THREAD

**Issue by kurtisnelson** [InflationX/ViewPump#21]
```
StrictMode    Used a non-SDK API
  android.os.strictmode.NonSdkApiUsedViolation: Landroid/view/LayoutInflater;->mConstructorArgs:[Ljava/lang/Object;
    at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
    at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
    at java.lang.Class.getDeclaredField(Native Method)
    at io.github.inflationx.viewpump.ReflectionUtils.getField(ReflectionUtils.java:15)
    at io.github.inflationx.viewpump.ViewPumpLayoutInflater.createCustomViewInternal(ViewPumpLayoutInflater.java:194)
    at io.github.inflationx.viewpump.ViewPumpLayoutInflater.access$000(ViewPumpLayoutInflater.java:14)
    at io.github.inflationx.viewpump.ViewPumpLayoutInflater$PrivateWrapperFactory2ViewCreator.onCreateView(ViewPumpLayoutInflater.java:405)
    at io.github.inflationx.viewpump.FallbackViewCreationInterceptor.intercept(FallbackViewCreationInterceptor.java:11)
    at io.github.inflationx.viewpump.InterceptorChain.proceed(InterceptorChain.java:37)
    at com.ubercab.presidio.font.core.FontOverrideViewpumpInterceptor.intercept(FontOverrideViewpumpInterceptor.java:31)
    at io.github.inflationx.viewpump.InterceptorChain.proceed(InterceptorChain.java:37)
    at io.github.inflationx.calligraphy3.CalligraphyInterceptor.intercept(CalligraphyInterceptor.java:18)
    at io.github.inflationx.viewpump.InterceptorChain.proceed(InterceptorChain.java:37)
    at io.github.inflationx.viewpump.ViewPump.inflate(ViewPump.java:49)
    at io.github.inflationx.viewpump.ViewPumpLayoutInflater$PrivateWrapperFactory2.onCreateView(ViewPumpLayoutInflater.java:385)
    at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:186)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:780)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
    at io.github.inflationx.viewpump.ViewPumpLayoutInflater.inflate(ViewPumpLayoutInflater.java:55)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
```

**Comment by hzsweers** [comment]
What's the alternative?

**Comment by kurtisnelson** [comment]
If there is not one we can file a bug on AOSP requesting this one become an official API.

**Comment by ZacSweers** [comment]
material components gets around it via https://github.com/material-components/material-components-android/blob/11ae93ddc1c1320771f8784571104add385403f9/lib/java/com/google/android/material/theme/MaterialComponentsViewInflater.java. Not sure if that's enough for us

**Comment by antalindisguise** [comment]
That library probably got whitelisted: https://developer.android.com/distribute/best-practices/develop/restrictions-non-sdk-interfaces#feature-request

BTW this is a problem with Android Q too.

**Comment by kanamares** [comment]
Yeap, on Android Q crash automatically. Any news on this @jbarr21

**Comment by masterjefferson** [comment]
Any updates on this one?

**Comment by ZacSweers** [comment]
@kanamares mind opening a separate issue for that? It seems like just a signature change rather than a non-sdk API issue. Unlikely we can do much about it before sources are released

**Comment by jbarr21** [comment]
we will investigate changing `ViewPumpLayoutInflator` to subclass [AppCompatLayout](http://androidxref.com/9.0.0_r3/xref/frameworks/support/v7/appcompat/src/main/java/androidx/appcompat/app/AppCompatViewInflater.java#254) to work around this

**Comment by MajaTrzebiatowska** [comment]
I'm not sure if that's just a matter of a signature change, please take a look here:
https://developer.android.com/preview/non-sdk-q

"Landroid/view/LayoutInflater;->mConstructorArgs:[Ljava/lang/Object;   # LayoutInflater's mConstructorArgs was being accessed for two reasons: reading and writing the context. When onCreateView() was called, the inflation context was not being passed, so if the developer wanted to get it, they had to read it from mConstructorArgs. When the developer wanted to create a view, with createView(), the developer could not adjust the view's constructor context. New APIs for createView() and onCreateView() were added that take the View Context as an argument.
"

**Comment by jbarr21** [comment]
The strict mode violation will continue on P, but new behavior has been introduced for Q

**Comment by chrisjenx** [comment]
@MajaTrzebiatowska when we get source code for that, we can re-visit to confirm, hopefully that new API will be cleaner than this fix, but I would like to see what they have done before making a change like that. 
(But I'm very glad they added that API, was super dumb setting a field to update the context inside a method you are calling).

This fix in place is much better than the previous attempt as we just force createView to use the context we supply to the LayoutInflater.
