### ISSUE TITLE
Crash when targeting Q

### ISSUE THREAD

**Issue by thanhtoan1196** [InflationX/ViewPump#65]
Version:
```
'io.github.inflationx:calligraphy3:3.1.1'
'io.github.inflationx:viewpump:2.0.3'
```

Logs:
```
2021-06-05 11:46:43.110 1482-1634/? E/WifiVendorHal: getWifiLinkLayerStats_1_3_Internal(l.936) failed {.code = ERROR_NOT_SUPPORTED, .description = }
2021-06-05 11:46:43.415 21342-21342/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mypackage.abcd, PID: 21342
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mypackage.abcd/com.mypackage2.xyz.ui.activity.login.LoginActivity_}: android.view.InflateException: Binary XML file line #17 in com.mypackage.abcd:layout/abc_screen_simple: Binary XML file line #17 in com.mypackage.abcd:layout/abc_screen_simple: Error inflating class androidx.appcompat.widget.FitWindowsLinearLayout
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3534)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3689)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2239)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7830)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1040)
     Caused by: android.view.InflateException: Binary XML file line #17 in com.mypackage.abcd:layout/abc_screen_simple: Binary XML file line #17 in com.mypackage.abcd:layout/abc_screen_simple: Error inflating class androidx.appcompat.widget.FitWindowsLinearLayout
     Caused by: android.view.InflateException: Binary XML file line #17 in com.mypackage.abcd:layout/abc_screen_simple: Error inflating class androidx.appcompat.widget.FitWindowsLinearLayout
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.reflect.Field.get(java.lang.Object)' on a null object reference
        at io.github.inflationx.viewpump.ReflectionUtils.getValue(SourceFile:1)
        at io.github.inflationx.viewpump.ViewPumpLayoutInflater.createCustomViewInternal(SourceFile:5)
        at io.github.inflationx.viewpump.ViewPumpLayoutInflater.access$000(SourceFile:1)
        at io.github.inflationx.viewpump.ViewPumpLayoutInflater$PrivateWrapperFactory2ViewCreator.onCreateView(SourceFile:3)
        at io.github.inflationx.viewpump.FallbackViewCreationInterceptor.intercept(SourceFile:3)
        at io.github.inflationx.viewpump.InterceptorChain.proceed(SourceFile:4)
        at io.github.inflationx.calligraphy3.CalligraphyInterceptor.intercept(SourceFile:1)
        at io.github.inflationx.viewpump.InterceptorChain.proceed(SourceFile:4)
        at io.github.inflationx.viewpump.ViewPump.inflate(SourceFile:2)
        at io.github.inflationx.viewpump.ViewPumpLayoutInflater$PrivateWrapperFactory2.onCreateView(SourceFile:8)
        at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:239)
        at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1086)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:999)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:963)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:659)
        at io.github.inflationx.viewpump.ViewPumpLayoutInflater.inflate(SourceFile:2)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(SourceFile:39)
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(SourceFile:2)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(SourceFile:6)
        at androidx.appcompat.app.AppCompatActivity.setContentView(SourceFile:1)
        at com.mypackage2.xyz.ui.base.BaseActivity.setContentView(SourceFile:1)
        at com.mypackage2.xyz.ui.activity.YBaseActivity.setContentView(SourceFile:1)
        at com.mypackage2.xyz.ui.activity.login.LoginActivity.setContentView(SourceFile:1)
2021-06-05 11:46:43.415 21342-21342/? E/AndroidRuntime:     at com.mypackage2.xyz.ui.activity.login.LoginActivity_.setContentView(SourceFile:1)
        at com.mypackage2.xyz.ui.activity.login.LoginActivity_.onCreate(SourceFile:7)
        at android.app.Activity.performCreate(Activity.java:7976)
        at android.app.Activity.performCreate(Activity.java:7965)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3505)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3689)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2239)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7830)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1040)
2021-06-05 11:46:43.436 1126-21675/? E/ResolverController: No valid NAT64 prefix (133, <unspecified>/0)
2021-06-05 11:46:43.475 1482-2780/? E/WindowManager: App trying to use insecure INPUT_FEATURE_NO_INPUT_CHANNEL flag. Ignoring
2021-06-05 11:46:43.619 1482-7053/? E/Process: get_ion_cache_memory: Unable to open /d/ion/system_stats
2021-06-05 11:46:43.625 1482-7053/? E/DatabaseUtils: Writing exception to parcel
    java.lang.IllegalArgumentException: Invalid column: title
        at com.android.providers.settings.SettingsProvider.normalizeProjection(SettingsProvider.java:2535)
        at com.android.providers.settings.SettingsProvider.query(SettingsProvider.java:657)
        at android.content.ContentProvider.query(ContentProvider.java:1224)
        at android.content.ContentProvider.query(ContentProvider.java:1317)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:271)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:104)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
2021-06-05 11:46:43.779 2872-2888/? E/hypnusd: submit dspfreq failed(Unknown error 524)
```

**Comment by ZacSweers** [comment]
Not enough information, feel free to revisit with more details
