### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by naveen-creater** [InflationX/ViewPump#68]
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.schwab.mobile.ssm/com.schwab.mobile.ssm.lms3.LMSLogin}: android.view.InflateException: Binary XML file line #60: Binary XML file line #60: Error inflating class android.webkit.WebView
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2434)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
       at android.app.ActivityThread.access$900(ActivityThread.java:157)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5551)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)

Caused by android.view.InflateException: Binary XML file line #60: Binary XML file line #60: Error inflating class android.webkit.WebView
       at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
       at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.inflate(-ViewPumpLayoutInflater.kt:57)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
       at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.inflate(-ViewPumpLayoutInflater.kt:48)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
       at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:401)
       at android.app.Activity.setContentView(Activity.java:2171)
       at com.schwab.mobile.ssm.lms3.LMSLogin.onCreate(LMSLogin.java:121)
       at android.app.Activity.performCreate(Activity.java:6272)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2387)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
       at android.app.ActivityThread.access$900(ActivityThread.java:157)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5551)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)

Caused by android.view.InflateException: Binary XML file line #60: Error inflating class android.webkit.WebView
       at android.view.LayoutInflater.createView(LayoutInflater.java:645)
       at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater$NameAndAttrsViewCreator.onCreateView(-ViewPumpLayoutInflater.kt:290)
       at io.github.inflationx.viewpump.internal.-FallbackViewCreationInterceptor.intercept(-FallbackViewCreationInterceptor.kt:14)
       at io.github.inflationx.viewpump.internal.-InterceptorChain.proceed(-InterceptorChain.kt:30)
       at io.github.inflationx.calligraphy3.CalligraphyInterceptor.intercept(CalligraphyInterceptor.java:18)
       at io.github.inflationx.viewpump.internal.-InterceptorChain.proceed(-InterceptorChain.kt:30)
       at io.github.inflationx.viewpump.ViewPump.inflate(ViewPump.kt:36)
       at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.onCreateView(-ViewPumpLayoutInflater.kt:169)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:694)
       at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.superOnCreateView(-ViewPumpLayoutInflater.kt:233)
       at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.access$superOnCreateView(-ViewPumpLayoutInflater.kt:19)
       at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater$ParentAndNameAndAttrsViewCreator.onCreateView(-ViewPumpLayoutInflater.kt:271)
       at io.github.inflationx.viewpump.internal.-FallbackViewCreationInterceptor.intercept(-FallbackViewCreationInterceptor.kt:14)
       at io.github.inflationx.viewpump.internal.-InterceptorChain.proceed(-InterceptorChain.kt:30)
       at io.github.inflationx.calligraphy3.CalligraphyInterceptor.intercept(CalligraphyInterceptor.java:18)
       at io.github.inflationx.viewpump.internal.-InterceptorChain.proceed(-InterceptorChain.kt:30)
       at io.github.inflationx.viewpump.ViewPump.inflate(ViewPump.kt:36)
       at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.onCreateView(-ViewPumpLayoutInflater.kt:151)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:762)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
       at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.inflate(-ViewPumpLayoutInflater.kt:57)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
       at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.inflate(-ViewPumpLayoutInflater.kt:48)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
       at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:401)
       at android.app.Activity.setContentView(Activity.java:2171)
       at com.schwab.mobile.ssm.lms3.LMSLogin.onCreate(LMSLogin.java:121)
       at android.app.Activity.performCreate(Activity.java:6272)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2387)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
       at android.app.ActivityThread.access$900(ActivityThread.java:157)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5551)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)

Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at android.view.LayoutInflater.createView(LayoutInflater.java:619)
       at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater$NameAndAttrsViewCreator.onCreateView(-ViewPumpLayoutInflater.kt:290)
       at io.github.inflationx.viewpump.internal.-FallbackViewCreationInterceptor.intercept(-FallbackViewCreationInterceptor.kt:14)
       at io.github.inflationx.viewpump.internal.-InterceptorChain.proceed(-InterceptorChain.kt:30)
       at io.github.inflationx.calligraphy3.CalligraphyInterceptor.intercept(CalligraphyInterceptor.java:18)
       at io.github.inflationx.viewpump.internal.-InterceptorChain.proceed(-InterceptorChain.kt:30)
       at io.github.inflationx.viewpump.ViewPump.inflate(ViewPump.kt:36)
       at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.onCreateView(-ViewPumpLayoutInflater.kt:169)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:694)
       at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.superOnCreateView(-ViewPumpLayoutInflater.kt:233)
       at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.access$superOnCreateView(-ViewPumpLayoutInflater.kt:19)
       at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater$ParentAndNameAndAttrsViewCreator.onCreateView(-ViewPumpLayoutInflater.kt:271)
       at io.github.inflationx.viewpump.internal.-FallbackViewCreationInterceptor.intercept(-FallbackViewCreationInterceptor.kt:14)
       at io.github.inflationx.viewpump.internal.-InterceptorChain.proceed(-InterceptorChain.kt:30)
       at io.github.inflationx.calligraphy3.CalligraphyInterceptor.intercept(CalligraphyInterceptor.java:18)
       at io.github.inflationx.viewpump.internal.-InterceptorChain.proceed(-InterceptorChain.kt:30)
       at io.github.inflationx.viewpump.ViewPump.inflate(ViewPump.kt:36)
       at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.onCreateView(-ViewPumpLayoutInflater.kt:151)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:762)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
       at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.inflate(-ViewPumpLayoutInflater.kt:57)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
       at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.inflate(-ViewPumpLayoutInflater.kt:48)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
       at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:401)
       at android.app.Activity.setContentView(Activity.java:2171)
       at com.schwab.mobile.ssm.lms3.LMSLogin.onCreate(LMSLogin.java:121)
       at android.app.Activity.performCreate(Activity.java:6272)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2387)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
       at android.app.ActivityThread.access$900(ActivityThread.java:157)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5551)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)

**Comment by ZacSweers** [comment]
without more details, unclear what the issue is. Unlikely to be viewpump, it just appears in the stacktrace because it participates in inflation
